# Generated by Django 2.2.6 on 2019-11-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191104_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fart',
            name='type',
            field=models.CharField(default='Simple Toot', max_length=32),
        ),
    ]
