# Generated by Django 2.2.6 on 2019-11-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191104_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fart',
            name='type',
            field=models.CharField(default='SBD', max_length=32),
        ),
    ]
