# Generated by Django 2.2.6 on 2019-11-04 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191104_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fart',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fartType', to='api.Type'),
        ),
    ]
