# Generated by Django 2.2.6 on 2019-12-18 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191104_1806'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='FartType',
        ),
        migrations.RenameField(
            model_name='fart',
            old_name='type',
            new_name='ftype',
        ),
    ]
